name: Sanitize and Truncate Git branch name
author: Neil Seligmann
description: Sanitize Git branch name to RFC-1123 standard
branding:
  icon: bold
  color: orange
inputs:
  branch-name:
    description: 'Branch Name'
    required: true
  max-length:
    description: 'Maximum length for the branch'
    required: false
    default: "64"
outputs:
  sanitized-branch-name:
    description: 'Sanitized Branch Name'
runs:
  using: 'node12'
  main: 'index.js'
